apiVersion: v1
kind: Pod
metadata:
  name: "<podname>" # pod name
spec:
  restartPolicy: Never # Ensure this is outside containers

  # Init container (runs before the main container)
  initContainers:
    - name: clone-git-repo
      image: alpine/git
      env: # Environment variables
        - name: GIT_USERNAME # GitHub username
          valueFrom:
            secretKeyRef:
              name: <github-secret>
              key: user
        - name: GIT_PASSWORD # GitHub Access Token
          valueFrom:
            secretKeyRef:
              name: <github-secret>
              key: token
      args:
        - clone
        - --verbose
        - --single-branch
        - --
        - # Git repository URL
        - /src/code
      volumeMounts:
        - name: git-repo
          mountPath: /src

  # Main container
  containers:
    - name: <container-name> # can be any name
      image: gitlab-registry.nrp-nautilus.io/<gitlab-username>/<gitlab-repo-name>:latest # GitLab registry image
      command: ["/bin/sh", "-c"]
      args:
        - |
          # Start SSH and keep the container running
          /usr/sbin/sshd && sleep infinity;
      resources: # Example resource request
        limits:
          memory: 16Gi
          nvidia.com/rtxa6000: 1
          cpu: 4
          ephemeral-storage: 200Gi
        requests:
          memory: 16Gi
          nvidia.com/rtxa6000: 1
          cpu: 4
          ephemeral-storage: 200Gi
      volumeMounts:
        - mountPath: /src
          name: git-repo

